#!/usr/bin/env python3

from __future__ import print_function

import sys
import argparse

from reflectrpc.rpcsh import ReflectRpcShell

parser = argparse.ArgumentParser(description="JSON-RPC shell")

parser.add_argument("host", metavar='HOST', type=str, help="Host to connect to")
parser.add_argument("port", metavar='PORT', type=int, help="Port to connect to")

parser.add_argument('-t', '--tls', default=False, action='store_true',
        help='Use TLS authentication and encryption on the RPC connection')

args = parser.parse_args()

try:
    shell = ReflectRpcShell(args.host, args.port)
    if args.tls:
        shell.enable_tls()
    shell.connect()
    shell.cmdloop()
except KeyboardInterrupt:
    sys.exit(0)
