# VM for developing ReflectRPC services with Python 3.5
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 5500, host: 5600

  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network"

  config.vm.synced_folder "../../examples/", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ReflectRPC-devpy3.5"
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y --no-install-recommends \
        python3 \
        python3-dev \
        python3-pip \
        python3-setuptools \
        gcc \
        libffi-dev \
        libssl-dev \
        libssl1.0.0 \
        vim \
        virtualbox-guest-utils
    apt remove -y python3-cryptography
    pip3 install reflectrpc
  SHELL
end
