# VM for developing ReflectRPC services with Python 2.7
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 5500, host: 5400

  config.vm.network "private_network", ip: "192.168.33.9"
  config.vm.network "public_network"

  config.vm.synced_folder "../../examples/", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ReflectRPC-devpy2.7"
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y --no-install-recommends \
        python \
        python-dev \
        python-pip \
        python-setuptools \
        gcc \
        libffi-dev \
        libssl-dev \
        libssl1.0.0 \
        vim \
        virtualbox-guest-utils
    apt remove python3 python3-minimal -y
    pip install reflectrpc
  SHELL
end
